version: '3.8'

services:
  postgres-db:
    image: postgres:13
    container_name: postgres-todo-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=todo_api
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: